# Generated by Django 4.0.1 on 2022-05-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_userquizpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizpoints',
            name='points',
            field=models.IntegerField(),
        ),
    ]
