# Generated by Django 4.0.1 on 2022-08-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_userquizpoints_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[(0, 'History'), (1, 'Geography'), (2, 'Sports'), (3, 'Entertainment'), (0, 'Music'), (1, 'Language'), (2, 'Gaming'), (3, 'Other')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
