# Generated by Django 4.0.1 on 2022-10-15 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_quiz_options_alter_userquizpoints_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcomments',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
