# Generated by Django 4.0.1 on 2022-10-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_usercommentrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercommentrelation',
            name='like',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
