# Generated by Django 4.0.1 on 2022-11-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_quiz_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('History', 'History'), ('1', 'Geography'), ('2', 'Sports'), ('3', 'Entertainment'), ('4', 'Music'), ('5', 'Language'), ('6', 'Gaming'), ('7', 'Other')], max_length=20),
        ),
    ]
