# Generated by Django 4.0.1 on 2022-11-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_alter_quiz_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('history', 'History'), ('geography', 'Geography'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('music', 'Music'), ('language', 'Language'), ('gaming', 'Gaming'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
