# Generated by Django 4.0.1 on 2022-12-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_alter_quiz_category_alter_quiz_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommentrelation',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
