# Generated by Django 4.0.1 on 2022-12-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_alter_usercommentrelation_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcomments',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
