# Generated by Django 4.0.1 on 2022-12-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_reportedcomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizcomments',
            name='reported',
        ),
    ]
