# Generated by Django 4.0.1 on 2022-12-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_remove_quizcomments_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedcomments',
            name='reason',
            field=models.CharField(default='Reason', max_length=160),
        ),
    ]
