# Generated by Django 4.0.1 on 2023-01-15 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0025_alter_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='Reason', max_length=160)),
                ('reportedbyuser', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_reported_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
