# Generated by Django 4.0.1 on 2023-01-26 14:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0031_alter_profile_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizComments',
            new_name='QuizComment',
        ),
        migrations.RenameModel(
            old_name='ReportedComments',
            new_name='ReportedComment',
        ),
    ]
