# Generated by Django 4.0.1 on 2023-01-26 16:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0032_rename_quizcomments_quizcomment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserQuizPoints',
            new_name='User_quiz_points',
        ),
        migrations.RenameModel(
            old_name='UserQuizRelation',
            new_name='User_quiz_relation',
        ),
    ]
